  version: '3'
  services:
    homeassistant:
      container_name: home-assistant
      image: homeassistant/raspberrypi3-homeassistant:latest
      volumes:
      #linux volume mount
        - /home/pi/homeassistant:/config
        - /etc/localtime:/etc/localtime:ro
      restart: always
      network_mode: host